<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caritas.Models\Caritas.Models.csproj" />
    <ProjectReference Include="..\Caritas.Repository\Caritas.Repository.csproj" />
  </ItemGroup>

</Project>
