// <auto-generated />
using System;
using System.Collections.Generic;
using Caritas.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caritas.Repository.Migrations
{
    [DbContext(typeof(CaritasDbContext))]
    [Migration("20260622201124_DoacaoUnificadaEntregaFamilia")]
    partial class DoacaoUnificadaEntregaFamilia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caritas.Models.Entities.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAtendimento")
                        .HasColumnType("date");

                    b.Property<string>("EncaminhamentosRealizados")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<string>("NecessidadesIdentificadas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParoquiaId")
                        .HasColumnType("integer");

                    b.Property<int?>("QtdMembrosTrabalhando")
                        .HasColumnType("integer");

                    b.Property<string>("Relato")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("RendaFamiliarMomento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("SituacaoGeral")
                        .HasColumnType("integer");

                    b.Property<int>("VoluntarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ParoquiaId");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("Caritas.Models.Entities.ConfiguracaoCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdParoquia");

                    b.ToTable("ConfiguracaoCesta", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("IdDoador")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdDoador");

                    b.HasIndex("IdParoquia");

                    b.ToTable("Doacao", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Doador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Doador", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdFamilia");

                    b.HasIndex("IdParoquia");

                    b.ToTable("Entrega", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("Tamanho")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Validade")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdParoquia");

                    b.HasIndex("IdItem", "IdParoquia", "Tamanho", "Validade", "Lote")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("IdItem", "IdParoquia", "Tamanho", "Validade", "Lote"), false);

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParoquiaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RendaFamiliar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SituacaoMoradia")
                        .HasColumnType("integer");

                    b.Property<int>("Vulnerabilidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("ParoquiaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Caritas.Models.Entities.FamiliaCidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FamiliaCidades");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Item", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Caritas.Models.Entities.ItemConfiguracaoCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAlimento")
                        .HasColumnType("integer");

                    b.Property<int>("IdConfiguracaoCesta")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadePacotes")
                        .HasColumnType("integer");

                    b.Property<int>("Tamanho")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdAlimento");

                    b.HasIndex("IdConfiguracaoCesta");

                    b.ToTable("ItemConfiguracaoCesta", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.LoteCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int?>("IdConfiguracaoCesta")
                        .HasColumnType("integer");

                    b.Property<int?>("IdDoacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdConfiguracaoCesta");

                    b.HasIndex("IdDoacao");

                    b.HasIndex("IdParoquia");

                    b.ToTable("LoteCesta", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.MovimentacaoCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEntrega")
                        .HasColumnType("integer");

                    b.Property<int>("IdLoteCesta")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEntrega");

                    b.HasIndex("IdLoteCesta");

                    b.HasIndex("IdParoquia");

                    b.ToTable("MovimentacaoCesta", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtualizadoPor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CriadoPor")
                        .HasColumnType("integer");

                    b.Property<int>("IdItem")
                        .HasColumnType("integer");

                    b.Property<int>("IdParoquia")
                        .HasColumnType("integer");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OrigemId")
                        .HasColumnType("integer");

                    b.Property<string>("OrigemTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("Tamanho")
                        .HasColumnType("integer");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly?>("Validade")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdParoquia");

                    b.HasIndex("IdItem", "IdParoquia");

                    b.HasIndex("OrigemTipo", "OrigemId");

                    b.ToTable("MovimentacaoEstoque", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Raiz")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estatico")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PerfilPaiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("PerfilPaiId");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificacaoAlternativa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("boolean");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TipoDocumentoAlternativo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataNasc")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<int>>("ParoquiasPermitidas")
                        .HasColumnType("integer[]");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("UsuarioAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("UsuarioCriadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.UsuarioParoquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ParoquiaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParoquiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioParoquia");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Alimento", b =>
                {
                    b.HasBaseType("Caritas.Models.Entities.Item");

                    b.Property<string>("FormaMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ToTable("Alimento", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Roupa", b =>
                {
                    b.HasBaseType("Caritas.Models.Entities.Item");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Condicao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estacao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FaixaEtaria")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.ToTable("Roupa", (string)null);
                });

            modelBuilder.Entity("Caritas.Models.Entities.Atendimento", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("ParoquiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Usuario", "Voluntario")
                        .WithMany()
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Paroquia");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("Caritas.Models.Entities.ConfiguracaoCesta", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Doacao", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Doador", "Doador")
                        .WithMany()
                        .HasForeignKey("IdDoador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doador");

                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Entrega", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Estoque", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.FamiliaCidade", "Cidade")
                        .WithMany("Familias")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("ParoquiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Paroquia");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Caritas.Models.Entities.ItemConfiguracaoCesta", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("IdAlimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.ConfiguracaoCesta", "ConfiguracaoCesta")
                        .WithMany("Itens")
                        .HasForeignKey("IdConfiguracaoCesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("ConfiguracaoCesta");
                });

            modelBuilder.Entity("Caritas.Models.Entities.LoteCesta", b =>
                {
                    b.HasOne("Caritas.Models.Entities.ConfiguracaoCesta", "ConfiguracaoCesta")
                        .WithMany()
                        .HasForeignKey("IdConfiguracaoCesta")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Caritas.Models.Entities.Doacao", "Doacao")
                        .WithMany()
                        .HasForeignKey("IdDoacao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfiguracaoCesta");

                    b.Navigation("Doacao");

                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.MovimentacaoCesta", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Entrega", null)
                        .WithMany()
                        .HasForeignKey("IdEntrega")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Caritas.Models.Entities.LoteCesta", "LoteCesta")
                        .WithMany()
                        .HasForeignKey("IdLoteCesta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", null)
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoteCesta");
                });

            modelBuilder.Entity("Caritas.Models.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Paroquia", null)
                        .WithMany()
                        .HasForeignKey("IdParoquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", "PerfilPai")
                        .WithMany("SubPerfis")
                        .HasForeignKey("PerfilPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PerfilPai");
                });

            modelBuilder.Entity("Caritas.Models.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Usuario", "UsuarioCriador")
                        .WithMany("UsuariosCriados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("Caritas.Models.Entities.UsuarioParoquia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany("UsuarioParoquias")
                        .HasForeignKey("ParoquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioParoquias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paroquia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Caritas.Models.Entities.Alimento", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Caritas.Models.Entities.Alimento", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Caritas.Models.Entities.Roupa", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Item", null)
                        .WithOne()
                        .HasForeignKey("Caritas.Models.Entities.Roupa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Caritas.Models.Entities.ConfiguracaoCesta", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Caritas.Models.Entities.FamiliaCidade", b =>
                {
                    b.Navigation("Familias");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.Navigation("UsuarioParoquias");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("SubPerfis");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioParoquias");

                    b.Navigation("UsuariosCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
