// <auto-generated />
using System;
using Caritas.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caritas.Repository.Migrations
{
    [DbContext(typeof(CaritasDbContext))]
    [Migration("20260523153222_EstadoInicial")]
    partial class EstadoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caritas.Models.Entities.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("RendaFamiliar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SituacaoMoradia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vulnerabilidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PerfilPaiId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("PerfilPaiId");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Caritas.Models.Entities.PerfilPermissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfilPermissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Permissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Escolaridade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("FamiliaId")
                        .HasColumnType("integer");

                    b.Property<string>("IdentificacaoAlternativa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("boolean");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataNasc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<long?>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<long?>("UsuarioCriadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("UsuarioCriadorId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Caritas.Models.Entities.UsuarioParoquia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ParoquiaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParoquiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioParoquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Pessoa", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Endereco", "Endereco")
                        .WithOne("Paroquia")
                        .HasForeignKey("Caritas.Models.Entities.Paroquia", "EnderecoId");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", "PerfilPai")
                        .WithMany("SubPerfis")
                        .HasForeignKey("PerfilPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PerfilPai");
                });

            modelBuilder.Entity("Caritas.Models.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Pessoa", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId");

                    b.HasOne("Caritas.Models.Entities.Usuario", "UsuarioCriador")
                        .WithMany("UsuariosCriados")
                        .HasForeignKey("UsuarioCriadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Perfil");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("Caritas.Models.Entities.UsuarioParoquia", b =>
                {
                    b.HasOne("Caritas.Models.Entities.Paroquia", "Paroquia")
                        .WithMany("UsuarioParoquias")
                        .HasForeignKey("ParoquiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caritas.Models.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioParoquias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paroquia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Endereco", b =>
                {
                    b.Navigation("Paroquia");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Familia", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Paroquia", b =>
                {
                    b.Navigation("UsuarioParoquias");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Perfil", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("SubPerfis");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");
                });

            modelBuilder.Entity("Caritas.Models.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioParoquias");

                    b.Navigation("UsuariosCriados");
                });
#pragma warning restore 612, 618
        }
    }
}
